// Incremental DataSet diff helper for GraphView.
//
// Filter chip toggles change which tasks are visible, so the graph's
// node/edge sets shift while the network instance, physics state, and
// camera position should stay alive. This module computes the minimal
// add/remove/update deltas between two graphData snapshots so GraphView
// can drive vis-data DataSet ops on the live instance instead of
// destroying and recreating the vis-network.
//
// Pure functions, no vis-network/JSX deps — unit-testable from a node
// vitest environment.

// Diff two snapshots by id. Returns:
//   addNodes        — nodes new in `next`. Full payload including x/y;
//                     vis-data DataSet.add() seeds the starting position.
//   updateNodes     — nodes present in both `prev` and `next`. x/y are
//                     STRIPPED before update because those are runtime
//                     properties owned by the physics body — mutating
//                     them would snap the node back to a stale seed and
//                     undo wherever physics or the user has placed it.
//                     Other attribute drift (status border, priority
//                     size, label, fill color, _task back-reference)
//                     IS pushed so upstream task updates propagate.
//   removeNodeIds   — ids in `prev` but not `next`.
//   addEdges        — full payload for new edges.
//   removeEdgeIds   — ids in `prev` but not `next`.
//
// Existing-edge updates are intentionally NOT computed here. The two
// fields that vary across renders are `length` (driven by the spring-
// length slider, which has its own update effect) and the visual color
// for cross-project depends-on edges (driven by the source/target task's
// project, which would change only on task moves — rare, and the next
// full rebuild reconciles it). Skipping them avoids redundant DataSet
// writes on every filter toggle.
//
// Both snapshots MUST be plain arrays of objects each carrying an `id`.
export function diffGraphData(prev, next) {
  const prevNodes = prev?.nodes || []
  const prevEdges = prev?.edges || []
  const nextNodes = next?.nodes || []
  const nextEdges = next?.edges || []

  const prevNodeIds = new Set()
  for (const n of prevNodes) prevNodeIds.add(n.id)
  const nextNodeIds = new Set()
  for (const n of nextNodes) nextNodeIds.add(n.id)

  const prevEdgeIds = new Set()
  for (const e of prevEdges) prevEdgeIds.add(e.id)
  const nextEdgeIds = new Set()
  for (const e of nextEdges) nextEdgeIds.add(e.id)

  const removeNodeIds = []
  for (const id of prevNodeIds) if (!nextNodeIds.has(id)) removeNodeIds.push(id)

  const addNodes = []
  const updateNodes = []
  for (const n of nextNodes) {
    if (prevNodeIds.has(n.id)) {
      // Existing — strip position fields. x/y belong to the live physics
      // body; the dataset's stored x/y is just the seed and should not
      // be re-pushed. Object spread + delete pattern is fine here:
      // graphData.nodes are short-lived plain objects regenerated by
      // useMemo on every render, so we're not mutating shared state.
      const stripped = { ...n }
      delete stripped.x
      delete stripped.y
      updateNodes.push(stripped)
    } else {
      addNodes.push(n)
    }
  }

  const removeEdgeIds = []
  for (const id of prevEdgeIds) if (!nextEdgeIds.has(id)) removeEdgeIds.push(id)
  const addEdges = []
  for (const e of nextEdges) if (!prevEdgeIds.has(e.id)) addEdges.push(e)

  return { removeNodeIds, addNodes, updateNodes, removeEdgeIds, addEdges }
}

// Apply a precomputed diff to a vis-data DataSet pair. Order:
//   1. Remove edges first so vis-data doesn't briefly hold edges that
//      reference about-to-be-removed nodes.
//   2. Remove dead nodes.
//   3. Update existing nodes (attribute drift; position untouched).
//   4. Add new nodes so a new edge always has both endpoints present.
//   5. Add new edges.
export function applyDiff(nodesDataSet, edgesDataSet, diff) {
  if (diff.removeEdgeIds.length > 0) edgesDataSet.remove(diff.removeEdgeIds)
  if (diff.removeNodeIds.length > 0) nodesDataSet.remove(diff.removeNodeIds)
  if (diff.updateNodes.length > 0) nodesDataSet.update(diff.updateNodes)
  if (diff.addNodes.length > 0) nodesDataSet.add(diff.addNodes)
  if (diff.addEdges.length > 0) edgesDataSet.add(diff.addEdges)
}
