#!/usr/bin/env node
// Sync repo-owned agent skills to the user-level Claude Code directory.
//
//   npm run sync:skills          # copy, reporting what changed
//   npm run sync:skills -- --check   # report drift only, exit 1 if any (CI)
//
// The repo is the source of truth. Three copies of each skill exist:
//
//   1. .claude/skills/<name>/        <- SOURCE. Edit here.
//   2. ~/.claude/skills/<name>/      <- generated by this script
//   3. inside the Atrium image       <- generated by `docker build` (COPY)
//
// (2) and (3) both derive from (1), so editing the source and rebuilding is
// enough to update everything. Without this script the user-level copy is
// hand-maintained, which is how two sets of instructions quietly start
// disagreeing — the failure mode being an agent that confidently follows the
// stale one.
//
// Symlinking would remove the drift risk entirely, but creating one on Windows
// requires Administrator (verified: "Administrator privilege required for this
// operation"), so a copy plus an explicit --check is the portable answer.

const fs = require('fs');
const os = require('os');
const path = require('path');

const REPO_SKILLS = path.join(__dirname, '..', '.claude', 'skills');
const USER_SKILLS = path.join(os.homedir(), '.claude', 'skills');
const CHECK_ONLY = process.argv.includes('--check');

// Skills the repo owns and therefore syncs. Deliberately an allow-list rather
// than "everything in .claude/skills": the user's own skills (atrium,
// project-guardrails, ...) live only at user level and must never be clobbered
// or deleted by this script.
const OWNED = ['containerize-project'];

function readIfExists(p) {
  try { return fs.readFileSync(p, 'utf8'); } catch { return null; }
}

// Compare ignoring line-ending differences — the repo may be checked out with
// CRLF on Windows, which would otherwise report permanent false drift.
function sameContent(a, b) {
  if (a === null || b === null) return false;
  return a.replace(/\r\n/g, '\n') === b.replace(/\r\n/g, '\n');
}

let drifted = 0;
let copied = 0;

for (const name of OWNED) {
  const srcDir = path.join(REPO_SKILLS, name);
  const dstDir = path.join(USER_SKILLS, name);

  if (!fs.existsSync(srcDir)) {
    console.error(`  MISSING SOURCE  ${name} — expected ${srcDir}`);
    process.exitCode = 1;
    continue;
  }

  for (const file of fs.readdirSync(srcDir)) {
    const src = path.join(srcDir, file);
    if (!fs.statSync(src).isFile()) continue;

    const dst = path.join(dstDir, file);
    const srcContent = fs.readFileSync(src, 'utf8');
    const dstContent = readIfExists(dst);

    if (sameContent(srcContent, dstContent)) {
      console.log(`  in sync         ${name}/${file}`);
      continue;
    }

    drifted += 1;
    if (CHECK_ONLY) {
      console.log(`  DRIFT           ${name}/${file}${dstContent === null ? ' (missing at user level)' : ''}`);
      continue;
    }

    fs.mkdirSync(dstDir, { recursive: true });
    fs.writeFileSync(dst, srcContent);
    copied += 1;
    console.log(`  ${dstContent === null ? 'installed' : 'updated  '}       ${name}/${file}`);
  }
}

console.log('');
if (CHECK_ONLY) {
  if (drifted) {
    console.log(`${drifted} file(s) out of sync. Run: npm run sync:skills`);
    process.exitCode = 1;
  } else {
    console.log('User-level skills match the repo.');
  }
} else {
  console.log(copied ? `Synced ${copied} file(s) to ${USER_SKILLS}` : 'Nothing to do — already in sync.');
  console.log('The image copy updates on the next `docker compose up -d --build`.');
}
